stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - params.yaml
    params:
    - data_ingestion.test_size
    outs:
    - data/raw/train.csv
    - data/raw/test.csv

  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv

  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - params.yaml
    params:
    - feature_engineering.max_features
    outs:
    - data/processed/train_tfidf.csv
    - data/processed/test_tfidf.csv
    - artifacts/tfidf_vectorizer.pkl

  model_building:
    cmd: python3 src/model_building.py
    deps:
    - src/model_building.py
    - data/processed/train_tfidf.csv
    - params.yaml
    params:
    - model_building.n_estimators
    - model_building.random_state
    - model_building.max_depth
    outs:
    - artifacts/model.pkl

  model_evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - artifacts/model.pkl
    - data/processed/test_tfidf.csv
    - params.yaml
    metrics:
    - dvclive/metrics.json
    plots:
    - dvclive/plots/metrics
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
