data_ingestion:
  test_size: 0.2

feature_engineering:
  max_features: 4000

model_building:
  model_name: nb      # rf / logreg / nb

models:
  rf:
    n_estimators: 500
    random_state: 42
    max_depth:
    class_weight: balanced

  logreg:
    max_iter: 2000
    C: 1.0
    class_weight: balanced

  nb:
    alpha: 1.0
