# data_ingestion:
#   test_size: 0.3
# feature_engineering:
#   max_features: 400
# model_building:
#   n_estimators: 200
#   random_state: 42
#   max_depth: null

data_ingestion:
  test_size: 0.2

feature_engineering:
  max_features: 4000

model_building:
  n_estimators: 500
  random_state: 42
  max_depth: null
